server:
  port: 7900
spring:
  application:
    name: provider
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ip-city?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cache.clusterNodes: 192.168.126.128:7000,192.168.126.128:7001,192.168.126.128:7002,192.168.126.128:7003,192.168.126.128:7004,192.168.126.128:7005,192.168.126.128:7006,192.168.126.128:7007,192.168.126.128:7008
    cache.commandTimeout: 5000
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka
logging:
  level:
    root: INFO