server:
  port: 9001
spring:
  application:
    name: consumer-feign
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: utf-8
    mode: HTML5
    suffix: .html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka
logging:
  level:
    root: INFO
feign:
  hystrix:
    enabled: true